export type WebhookEventType =
  | 'RUN_STARTED'
  | 'RUN_COMPLETED'
  | 'RUN_FAILED'
  | 'TEST_FAILED'
  | 'PLAN_COMPLETED'
  | 'BUG_REPORT_CREATED';

export const ALL_WEBHOOK_EVENTS: WebhookEventType[] = [
  'RUN_STARTED',
  'RUN_COMPLETED',
  'RUN_FAILED',
  'TEST_FAILED',
  'PLAN_COMPLETED',
  'BUG_REPORT_CREATED',
];

/** SLACK also covers Mattermost, Rocket.Chat and Discord's `/slack` endpoint (PRD-031). */
export type WebhookFormat = 'GENERIC' | 'SLACK' | 'TEAMS';

export const ALL_WEBHOOK_FORMATS: WebhookFormat[] = ['GENERIC', 'SLACK', 'TEAMS'];

export interface Webhook {
  id: string;
  /** Masked (scheme + host + last 4 characters) for chat formats: the URL is the credential. */
  url: string;
  events: WebhookEventType[];
  active: boolean;
  format: WebhookFormat;
  createdAt: string;
  updatedAt: string;
}

export interface CreateWebhookRequest {
  url: string;
  /** Required for GENERIC; generated by the server for chat formats when omitted. */
  secret?: string;
  events: WebhookEventType[];
  active: boolean;
  format: WebhookFormat;
}

/** Omitted `url`, `secret` or `format` keep the stored value. */
export interface UpdateWebhookRequest {
  url?: string;
  secret?: string;
  events: WebhookEventType[];
  active: boolean;
  format?: WebhookFormat;
}

export interface WebhookDelivery {
  id: string;
  event: WebhookEventType;
  responseStatus: number | null;
  attempt: number;
  success: boolean | null;
  error: string | null;
  createdAt: string;
}
